
import os

from datetime import datetime

from reportlab.lib import colors

from reportlab.lib.pagesizes import A4

from reportlab.lib.styles import (
    getSampleStyleSheet
)

from reportlab.lib.units import inch

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Image,
    PageBreak
)


# ==========================================================
# GENERATE PDF REPORT
# ==========================================================

def generate_pdf_report(
    data,
    report_folder
):

    # ------------------------------------------------------
    # CREATE UNIQUE PDF NAME
    # ------------------------------------------------------

    timestamp = datetime.now().strftime(
        "%Y%m%d_%H%M%S"
    )


    pdf_filename = (
        f"automated_report_{timestamp}.pdf"
    )


    pdf_path = os.path.join(
        report_folder,
        pdf_filename
    )


    # ------------------------------------------------------
    # CREATE PDF DOCUMENT
    # ------------------------------------------------------

    document = SimpleDocTemplate(
        pdf_path,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )


    styles = getSampleStyleSheet()


    story = []


    # ------------------------------------------------------
    # TITLE
    # ------------------------------------------------------

    story.append(
        Paragraph(
            "Automated Email Report",
            styles["Title"]
        )
    )


    story.append(
        Spacer(
            1,
            10
        )
    )


    story.append(
        Paragraph(
            f"Source File: {data['filename']}",
            styles["Normal"]
        )
    )


    story.append(
        Paragraph(
            "Generated by Automated Email "
            "Report Generator",
            styles["Normal"]
        )
    )


    story.append(
        Spacer(
            1,
            20
        )
    )


    # ------------------------------------------------------
    # DATA SUMMARY
    # ------------------------------------------------------

    story.append(
        Paragraph(
            "Data Summary",
            styles["Heading2"]
        )
    )


    summary_data = [

        [
            "Total Records",
            str(
                data["total_records"]
            )
        ],

        [
            "Total Columns",
            str(
                data["total_columns"]
            )
        ],

        [
            "Numeric Columns",
            str(
                len(
                    data["numeric_columns"]
                )
            )
        ]

    ]


    summary_table = Table(
        summary_data,
        colWidths=[
            3 * inch,
            2 * inch
        ]
    )


    summary_table.setStyle(
        TableStyle([

            (
                "BACKGROUND",
                (0, 0),
                (-1, -1),
                colors.lightgrey
            ),

            (
                "GRID",
                (0, 0),
                (-1, -1),
                1,
                colors.grey
            ),

            (
                "PADDING",
                (0, 0),
                (-1, -1),
                8
            )

        ])
    )


    story.append(
        summary_table
    )


    story.append(
        Spacer(
            1,
            20
        )
    )


    # ------------------------------------------------------
    # STATISTICAL ANALYSIS
    # ------------------------------------------------------

    story.append(
        Paragraph(
            "Statistical Analysis",
            styles["Heading2"]
        )
    )


    for column, stats in data[
        "statistics"
    ].items():


        statistics_data = [

            [
                "Column",
                column
            ],

            [
                "Total",
                str(
                    stats["total"]
                )
            ],

            [
                "Average",
                str(
                    stats["average"]
                )
            ],

            [
                "Maximum",
                str(
                    stats["maximum"]
                )
            ],

            [
                "Minimum",
                str(
                    stats["minimum"]
                )
            ]

        ]


        statistics_table = Table(
            statistics_data,
            colWidths=[
                2 * inch,
                3 * inch
            ]
        )


        statistics_table.setStyle(
            TableStyle([

                (
                    "GRID",
                    (0, 0),
                    (-1, -1),
                    1,
                    colors.grey
                ),

                (
                    "BACKGROUND",
                    (0, 0),
                    (0, -1),
                    colors.lightgrey
                ),

                (
                    "PADDING",
                    (0, 0),
                    (-1, -1),
                    6
                )

            ])
        )


        story.append(
            statistics_table
        )


        story.append(
            Spacer(
                1,
                15
            )
        )


    # ------------------------------------------------------
    # CHARTS
    # ------------------------------------------------------

    story.append(
        PageBreak()
    )


    story.append(
        Paragraph(
            "Data Visualization",
            styles["Heading2"]
        )
    )


    for chart_filename in data[
        "chart_files"
    ]:


        chart_path = os.path.join(
            report_folder,
            chart_filename
        )


        if os.path.exists(
            chart_path
        ):

            story.append(
                Image(
                    chart_path,
                    width=6.5 * inch,
                    height=3.8 * inch
                )
            )


            story.append(
                Spacer(
                    1,
                    15
                )
            )


    # ------------------------------------------------------
    # BUILD PDF
    # ------------------------------------------------------

    document.build(
        story
    )


    return pdf_filename